name: Waka Readme

on:
  schedule:
    # Runs at 12am UTC
    - cron: "1 0 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/Profile-Readme-WakaTime@master
        with:
          WAKATIME_API_KEY: ${{ secrets.API_TOKEN_WAKA_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          BRANCH: "master"
          COMMIT_MSG: "Automated Coding Activity Update"
