name: Waka Readme

on:
  schedule:
    # Runs at 12am UTC
    - cron: "1 0 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.API_TOKEN_WAKA_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          COMMIT_MESSAGE: "Automated Coding Activity Update"
          SHOW_TITLE: true
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          TIME_RANGE: last_6_months
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          
          
          
          
