name: Update README stats

on:
  workflow_dispatch:
    shedule:
    # Runs every 2 hours
    - cron: "0 */2 * * *"

jobs:

  # Update README stats
  update-readme:
   name: Update README 
    runs-on: ubuntu-latest
    steps:
    - uses: athul/waka-readme@master
      with:
      WAKATIME_API_KEY: ${{ secrets.API_TOKEN_WAKA_KEY }}