name: Waka Readme

on:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.API_TOKEN_WAKA_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN  }}
          COMMIT_MESSAGE: "Automated Coding Activity Update"
          SHOW_LINES_OF_CODE: true
          SHOW_DAYS_OF_WEEK: false
          SHOW_OS: true
          SHOW_PROJECTS: false
          SHOW_EDITORS: true
          
          
          
